### ISSUE TITLE
Use argparse to parse command line arguments

### ISSUE THREAD

**Issue by itsnauman** [joh/when-changed#24]
Argparse is a much more cleaner solution to parsing the command line arguments. It will make the code more pythonic :hamburger:

**Comment by joh** [comment]
There's a pull request for adding argparse, but it hasn't been accepted yet: https://github.com/joh/when-changed/pull/21

**Comment by Cypher1** [comment]
No pull requests now, is this done?

**Comment by joh** [comment]
The pull request was closed due to inactivity, i.e. it wasn't merged due to some issues.
