### ISSUE TITLE
`watched` set is not modified

### ISSUE THREAD

**Issue by zerkms** [joh/when-changed#30]
Is it intentionally that `watched` `Set` initialized at https://github.com/joh/when-changed/blob/master/whenchanged%2Fwhenchanged.py#L100 is then addressed twice to check presence of elements but is never modified?

**Comment by joh** [comment]
Hmm, no that looks like a bug. The path should be added to the watched set after wm.add_watch().

**Comment by joh** [comment]
Looks like there's no need to maintain a ``watched`` set with pyinotify. From the [API documentation of WatchManager.add_watch()](http://seb.dbzteam.org/pyinotify/pyinotify.WatchManager-class.html#add_watch):

> If |path| is already watched it is ignored, but if it is called with option rec=True a watch is put on each one of its not-watched subdirectory.
