### ISSUE TITLE
Hide any output of given command/s

### ISSUE THREAD

**Issue by pschwede** [joh/when-changed#31]
Hello,

I cannot stop it making prints to stdout or stderr.
Could there be an option for that, please?

Thanks.

**Comment by juckele** [comment]
Hey, @pschwede, are you using would it be possible for you to redirect stdout and stderr to /dev/null?

If you need help with redirection, you can start here: http://stackoverflow.com/questions/6674327/redirect-all-output-to-file

What's the use case that you're trying to achieve that you want to suppress some or all output?

**Comment by pschwede** [comment]
Thanks.. just redirecting stderr worked fine!

I have a Makefile which sets up my develop workbench. Before starting vim, it is starting when-changed.

```Makefile
develop:
  when-changed app/index.html coffe/main.coffee app/css/style.css -c make --silent rebuild 2> /dev/null &
  vim -S session.vim
  pkill when-changed
```

**Comment by juckele** [comment]
Great, glad that helped your situation. :+1:

**Comment by joh** [comment]
I guess a `-q` (quiet) option could be useful :)

**Comment by eviweb** [comment]
Hi,
should the quiet option disable `stdout` and `stderr` ?
Should it also disable log message ?
Thanks

**Comment by eviweb** [comment]
Is that https://github.com/joh/when-changed/compare/master...eviweb:fix-issue-31 could do the trick ?
It disables `stdout` and `stderr` only for the run command.

**Comment by joh** [comment]
> Hi,
> should the quiet option disable both `stdout` and `stderr` ?
> Should it also disable log message ?
> Thanks

Quiet option should only suppress non-error messages, i.e. only stdout.
Log message, you mean those produced by -v right? I guess they can remain independent, i.e. -q -v should suppress stdout from the command, but still print log messages.

**Comment by eviweb** [comment]
Done https://github.com/joh/when-changed/pull/79
