### ISSUE TITLE
Allow wildcards/patterns as FILE argument

### ISSUE THREAD

**Issue by atypic** [joh/when-changed#34]
Example: when-changed *.tex xelatex %f

**Comment by joh** [comment]
This is already supported if you use ```-c```:

```when-changed *.tex -c xelatex %f```

**Comment by atypic** [comment]
awesome!

**Comment by acrolink** [comment]
The code `when-changed *.tex -c xelatex %f` works fine but I want to ask how to do the same for let's say `*.tex` files inside a certain directory and all its folders? Thank you.

**Comment by joh** [comment]
@acrolink Issue #16 is a related feature request, but is about excluding files.

**Comment by yuriescl** [comment]
Wildcard/pattern support isn't described in `--help` and `README` outputs (v0.3.0).
Also, it would be interesting to have support for glob patterns, something like a -g option, similar to how [ripgrep globs work](https://www.mankier.com/1/rg#-g) (exclusion would be possible by preceding the glob with a `!`).
