### ISSUE TITLE
Runs twice

### ISSUE THREAD

**Issue by uros-stegic** [joh/when-changed#44]
It runs command twice after my file has changed. In file test.js i have:
`console.log('Hello world!');`

and after setting when-changed like this:
`when-changed test.js node test.js`

I get node called twice. Maybe it's worth to mention that I have Python3 as my main Python interpreter.

**Comment by joostsijm** [comment]
Try using the -1 flag

**Comment by senorjohnny** [comment]
With -1 flags runs fine, only once. Not sure if I need that flag since no one changes this input file. I presume that node touches the file so access time changes.

**Comment by joh** [comment]
Either that, or your editor may touch the file twice on save..?

**Comment by uros-stegic** [comment]
Nope, Vim doesn't do things like that. It has to be something with node, since python, php and lots of other stuff doesn't do this, only happens with node.
