### ISSUE TITLE
-r argument unnecessary?

### ISSUE THREAD

**Issue by jtpereyda** [joh/when-changed#53]
While trying to figure out what -r does, I found that `when-changed` behaves recursively, even if you specify a directory without using -r.

As long as this is the case, can we get rid of -r and just make it the default?

[`WhenChanged.__init__`](https://github.com/joh/when-changed/blob/85de2f23bd7b989b9d3fbce58a7ccc31ffbdc129/whenchanged/whenchanged.py#L49) will automatically pass the recursive argument to `watchdog.observers.Observer`. However, -r will still matter in [`WhenChanged.is_interested`](https://github.com/joh/when-changed/blob/85de2f23bd7b989b9d3fbce58a7ccc31ffbdc129/whenchanged/whenchanged.py#L83), which is used by `WhenChanged.on_change`.

So either the setting is not exactly necessary, or I am misunderstanding its purpose.

**Comment by joh** [comment]
Yes, we watch recursively in `watchdog.observers.Observer` but ignore files in subdirectories in [`WhenChanged.is_interested()`](https://github.com/joh/when-changed/blob/85de2f23bd7b989b9d3fbce58a7ccc31ffbdc129/whenchanged/whenchanged.py#L90) if `recursive` is `False`. See lines 90-98.

**Comment by jtpereyda** [comment]
So what does the -r parameter currently do from a user's perspective?

**Comment by joh** [comment]
It does exactly what it claims to do: with -r, the command will be executed also for changed files in subdirs (recursively).

Try it and see:
```
$ ./when-changed -v ./ echo %f changed &
When './' changes, run 'echo %f changed'
$ touch file
/home/joh/code/when-changed/file changed
$ touch dir/file
# nothing printed
```

```
$ ./when-changed -v ./ echo %f changed &
When './' changes, run 'echo %f changed'
$ touch file
/home/joh/code/when-changed/file changed
$ touch dir/file
/home/joh/code/when-changed/dir/file changed
```

**Comment by jtpereyda** [comment]
I see, so without `-r` there is only one level of recursion. I expected it to only watch the directory itself for changes if not using `-r`, but maybe it's more obvious to others...

**Comment by jtpereyda** [comment]
I can't think of how to make it clearer; it seems obvious in retrospect... thanks for the answers, and for writing and maintaining this very handy tool.
