### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by imlordeyaya** [joh/when-changed#54]
Hello, I cannot find any examples using this and I'm still getting syntax error. My code is
`
import watchdog
import whenchanged
import subprocess32

when-changed funcaptcha.png print("funcaptcha changed")
`

File is in the same folder as python script. Im using python 2.7

**Comment by joh** [comment]
Not sure what you're trying to do here. `when-changed` is a command-line program, so you don't need to write any python code to use it. Try the following instead:
`when-changed funcaptcha.png echo "funcaptcha changed"`
