### ISSUE TITLE
get the last X lines the added to the file 

### ISSUE THREAD

**Issue by ItamarShDev** [joh/when-changed#56]
is it possible to get the changes made to the file as an argument to the command?

**Comment by Cypher1** [comment]
I think the following is roughly what you're looking for for a single file. I don't think it is supported by when-changed.

`when-changed test_file -c "touch /tmp/test_file; diff test_file /tmp/test_file > diff; cp test_file /tmp/test_file; cat diff`

You should be able to make this into a function fairly easily.
