### ISSUE TITLE
Command runs twice

### ISSUE THREAD

**Issue by vacovnik** [joh/when-changed#59]
Hi!
Thank you for a good work so far!

I have an issue though... I'm running Ubuntu 16.04 and when-changed sometimes executes my command two times when run like so:

when-changed * -c ./pushGit.sh

pushGit.sh:
#!/bin/bash

git commit -am 'save'
git push

Thanks again and have a nice day!

**Comment by joh** [comment]
Some files are probably modified due to the `git commit`. Can you try `when-changed -1 ...` ?

**Comment by joh** [comment]
Also, `-v` should give you some more information about which files were modified.

**Comment by vacovnik** [comment]
Oh....
Next time I'll try to read manual before asking...
Thanks for your reply!
By the way, `-v` does not print out changed file for me... It prints some fancy text with all files it is watching, but nothing after that.
