### ISSUE TITLE
Not working with git log

### ISSUE THREAD

**Issue by goldylucks** [joh/when-changed#83]
Thank you so much for this project!

Anything I'm doing wrong?

![Peek 2019-08-04 20-27](https://user-images.githubusercontent.com/6963212/62427093-435eb100-b6f6-11e9-87d4-998303be5b6c.gif)

The same command works with linux's built in `watch`:

![Peek 2019-08-04 20-29](https://user-images.githubusercontent.com/6963212/62427110-8fa9f100-b6f6-11e9-8fc2-769969215185.gif)

**Comment by joh** [comment]
Interesting use case! By default, .git directories are ignored by when-changed. See https://github.com/joh/when-changed/blob/master/whenchanged/whenchanged.py#L53
You can comment out that line and it should work.

**Comment by goldylucks** [comment]
Thanks for the response!

I commented that line out, restarted gnome, opened a fresh terminal, and still doesn't work :/

any other ideas we can try?

**Comment by joh** [comment]
Hmm, it works for me here. Did you remember to install your modified version with ```pip install .```?

Btw, to run git log whenever you change branches it might be better to watch .git/HEAD...

**Comment by goldylucks** [comment]
> Hmm, it works for me here

So now it only refreshes if I focus on the terminal and press `q`. For you it refreshes automatically when you change a branch or add a commit?

I can't get that to work :/

Do you have a vid/gif showing it in action? to make sure we are talking about the same behavior here.

**Comment by joh** [comment]
Ah, your git log is probably waiting for pager input. Try with ```git --no-pager log``` instead.

**Comment by goldylucks** [comment]
ok that works, thanks for pointing that out!
now I'm seeing many "re-renders" of git log when I make a change:

![whe-changed](https://user-images.githubusercontent.com/6963212/64686398-4a18da80-d491-11e9-9d4c-806e2e6ac10f.gif)

TBH, working with `watch` is fine by me, just would be nice to not poll if I can listen to changes, but don't sweat about it, so feel free to close this issue.

my idea might be a very edgy use case

**Comment by joh** [comment]
You could try the `-1` option. Also maybe use `clear && git --no-pager log` as the command.
