### ISSUE TITLE
pyinotify incompabilities

### ISSUE THREAD

**Issue by psporysz** [joh/when-changed#9]
Since the project uses pyinotify to listen on changes, it is no longer able to do the job in case of Windows OS. Also, It does not work on Linux Guest OS under Windows host in VirtualBox when you are polling files shared with vboxsf module. Codebase is small thus anyone could adjust it a bit to do own job without learning something bigger like http://pythonhosted.org/watchdog/. So far it was very platform-independent. I think kind of fallback would be nice.

**Comment by ysangkok** [comment]
If a polling mechanism is to be implemented as a fallback: When the file getting watched is deleted, is it best to regard the file as unchanged, as I believe inotify does, or is it best to keep statting for every poll and fail if the file does not exist?

And if when-changed is called on a mounted filesystem that does not support inotify (how do we check this?), should when-changed automatically try to poll instead?

**Comment by joh** [comment]
The latest 0.3.0 release is cross-platform and should also work on Windows :)
